id: P28525982
initial_creation_type: input
source_metadata:
  title: Drikung Kyobpa Jikten Sumgön
  language: en
  description: 'Texts by and about Drikung Kyobpa Jikten Sumgön (''bri gung skyob
    pa ''jig rten gsum mgon, 1143–1217), founder of the Drikung Kagyü tradition:'
  volume:
    e306700a2a544a43af9aab4ebba51c94:
      title: In Praise of Padmākara, the Great Guru of Uḍḍiyāna
      parent: Praise
    7fdaf28db1d548ffabe072d08a5ad8a5:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Praise
    741d3951406e49fa8c14891694408447:
      title: Verses in Praise of the Protector Akṣobhya
      parent: Praise
    cd7a9652d4e241efa886bfe17eb5560e:
      title: 'Prayer to Tārā: A Sevenfold Supplication for Protection'
      parent: Prayers
created_at: '2022-02-28T23:03:51.357579'
last_modified_at: '2022-02-28T23:03:51.357584'
